version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "127.0.0.1:9002:9000"      # S3 API
      - "127.0.0.1:9003:9001"      # MinIO Console
    environment:
      MINIO_ROOT_USER: ${S3_ADMIN}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  postgres_data:
  minio_data:
